l-lin/angular-datatables

demo/advanced/rowSelect.js
This is not necessary but in my opinion is actually good to have to show the complete example.
Added toggle one to set the check state of the title header checkbox.
For example, if all rows are checked, automatically mark the header
checkbox checked and vice versa.
Signed-off-by: Jack Yen <jack@jackyen.com>
=> Improve doc example

dist/angular-datatables.js
There were some odd characters floating around in the JavaScript file angular-datatables.js. I have removed these characters however the minified file will also be buggy. So please re-compile! The characters were found on lines 975, 978, and 1140. Cheers :)
=> Fix characters in angular-datatables.js

dist/angular-datatables.js
… but angular-datatables only works with raw HTML
- pass $scope into showLoading(), which passes to DTLoadingTemplate.compileHtml(), which can then compile the HTML which can contain directives
- DTLoadingTemplate can then be overridden, with a custom html variable that can now contain directives
=> Add support for directives in the DTLoadingTemplate

src/angular-datatables.factory.js, src/angular-datatables.options.js
A very small fix of two typos I happen to find in the comments.
I didn't touch the dist/ folder files since I'm not sure how/when those are updated.
=> Fix typos in the comments

src/angular-datatables.renderer.js
There are some invisible characters in the file that are causing troubles when building Docker image of AngularJS application using angular-datatables module.
=> Remove invisible characters in angular-datatables.renderer.js

bower.json
According to the upstream website of DataTables,
and the bower-based webjars for its plugins,
“datatables.net” is its official and correct
package name, not “datatables” which exists only
as a legacy alias (the content is identical, I checked).
=> Fix datatables dependency

src/angular-datatables.renderer.js
The regular expression searching for the `` comment directive was not matching correctly when the binding contained a `$`, like `item in $ctrl.items`.
This change adds the `$` to the matched symbols.
=> Added $ to the ng-repeat directive comment regex

README.md
`bower install` command in Angular 1.x branch was installing `angular-datatables` ^2.x versions.
=> Update readme for Angular 1.x branch. [bower command update] 

bower.json
Hi!
I founded that bug, when tried zero configuration example with release **0.5.5** and **bower**;
With release 0.5.4 or NPM it's all ok!
**How to reproduce?**
1. bower i angular-datatables#0.5.5
2. Create code from example http://l-lin.github.io/angular-datatables/archives/#/zeroConfig
Add to index.html scripts and css:
- <script src="bower_components/jquery/dist/jquery.min.js"></script>
- <script src="bower_components/datatables.net/media/js/jquery.dataTables.min.js"></script>
- <script src="bower_components/angular/angular.min.js"></script>
- <script src="bower_components/angular-datatables/dist/angular-datatables.min.js"></script>
- <>link rel="stylesheet" href="bower_components/angular-datatables/dist/css/angular-datatables.css">
**Problem:**
Styles on table incorrect, missing …
=> Add missing dependency datatables.net-dt in bower for releases >=0.5.5;

package.json, src/angular-datatables.directive.ts
- Rename rm to rimraf for compatibility under windows
- Version number update to remove npm warn: "requires a peer of"
- Remove the unnecessary $.extend of default options which is buggy when using bootstrap extension
- https://jsfiddle.net/2e41vvje/
- empty extend is not needed according to: https://datatables.net/examples/basic_init/zero_configuration.html and https://datatables.net/examples/styling/bootstrap.html
=> Package.json version update and default options bug fix

demo/src/app/basic/server-side-angular-way-snippet.component.ts, demo/src/app/basic/server-side-angular-way.component.ts
Fixes a bug where the table won't display the "No data!" message when the API returns an empty array in the very first call. This happens because the `this.persons` array is already initialized with an empty array within the class, so it's not updated when it receives another empty array from the API. The table gets overwritten by DataTables and erases the "no data" message.
Also fixes the indentation on snippets to match the 2 spaces used throughout the project.
=> Fix the Server Side the Angular way example

src/angular-datatables.renderer.js
Change: angular-datatables show the 'loading' template just before the table gets destroyed.
=> Fix for #1299: Ugly Re-render in Angular "ng" mode.

README.md, package-lock.json, package.json, schematics/.editorconfig, schematics/.gitignore, schematics/.npmignore, schematics/src/collection.json, schematics/src/ng-add/index.ts, schematics/src/ng-add/schema.json, schematics/tsconfig.json
Simplifies installation process with a single `ng add` command.
=> Feat: ng add support

demo/src/app/advanced/router-link-snippet.component.ts
`Renderer` is deprecated in Angular v10. I updated the code to include usage snippet with `Renderer2`
Closes #1476
=> docs(demo): Add Renderer2 support for Router Link snippet

.github/workflows/publish.yml, DEVELOPER.md, package.json
After some thoughts, it's not a must to set the version `x.y.z-dev` since it's not published in NPM.
It's also not mandatory to update the demo version as it's not used on NPM packages or anything else.
=> build(#1505): add publish workflow

demo/src/app/advanced/demo-ng-template-ref-event-type.ts, demo/src/app/advanced/demo-ng-template-ref.component.html, demo/src/app/advanced/demo-ng-template-ref.component.ts, demo/src/app/advanced/using-ng-template-ref.component.html, demo/src/app/advanced/using-ng-template-ref.component.ts, demo/src/app/app.component.html, demo/src/app/app.module.ts, demo/src/app/app.routing.ts, demo/src/assets/docs/advanced/using-ng-template-ref/intro.md, demo/src/assets/docs/advanced/using-ng-template-ref/source-html.md, demo/src/assets/docs/advanced/using-ng-template-ref/source-ts.md, src/angular-datatables.directive.ts, src/models/settings.ts
- Adds support for injecting dynamic Angular code in a HTML table using `Renderer2` and `TemplateRef`. 
- Can be used to inject Angular components as demonstrated in the demo project.
=> [Feature] Add TemplateRef support

demo/src/app/base-demo/base-demo.component.html, demo/src/app/base-demo/base-demo.component.ts
**Fixed console error in base-demo.component on the Docs website.**
Replaced the HTML bookmarks for Preview, HTML and TypeScript with a function call which will enable the smooth scroll effect.
=> [Demo Project] changed html bookmarks to scrollToElement function

demo/package-lock.json, demo/src/app/advanced/custom-range-search.component.spec.ts, demo/src/app/advanced/dt-instance.component.spec.ts, demo/src/app/advanced/individual-column-filtering.component.spec.ts, demo/src/app/advanced/load-dt-options-with-promise.component.spec.ts, demo/src/app/advanced/multiple-tables.component.spec.ts, demo/src/app/advanced/rerender.component.spec.ts, demo/src/app/advanced/router-link.component.spec.ts, demo/src/app/advanced/row-click-event.component.spec.ts, demo/src/app/advanced/using-ng-pipe.component.spec.ts, demo/src/app/advanced/using-ng-template-ref.component.spec.ts, demo/src/app/advanced/using-ng-template-ref.component.ts, demo/src/app/app.component.spec.ts, demo/src/app/basic/angular-way.component.spec.ts, demo/src/app/basic/server-side-angular-way.component.spec.ts, demo/src/app/basic/with-ajax.component.spec.ts, demo/src/app/basic/with-options.component.spec.ts, demo/src/app/basic/zero-config.component.spec.ts, demo/src/tsconfig.spec.json
I'm opening this PR as continuation to #1529 I couldn't re-open my previous PR so here we go again!
**Features:**
Provides unit tests for following entities:
[ x ] Basic examples
[ x ] Advanced examples
Unit test for NgTemplateRef component isn't working due to a race condition with `dtOptions` `Input` binding on the directive and `dtTrigger` inside component's `ngAfterViewInit`.
I might cover unit tests for Extensions examples in a future PR but this takes precendence.   
Closes #1513
=> Add unit tests to demo project

schematics/src/ng-add/index.ts, schematics/src/ng-add/models/style-options.ts, schematics/src/ng-add/schema.json
- Add Bootstrap 5 CSS
- Upgrade deps
=> Upgrade ng-add deps

demo/src/app/advanced/using-ng-pipe.component.spec.ts, demo/src/app/advanced/using-ng-pipe.component.ts, demo/src/app/app.module.ts, demo/src/assets/docs/advanced/using-ng-pipe/source-ts.md, src/angular-datatables.directive.ts, src/models/settings.ts
Hi,
I added the `ngPipeArgs` option with a test in `demo/src/app/advanced/using-ng-pipe.component.spec.ts` file. I chose to take the data ID and convert it to currency because I didn't know how to import data.
I also saw that the responsive installation was wrong, I decided to fix it.
Finally, this is my first pull request, if I did something wrong, don't hesitate to tell me.
Regards,
Adrien.
=> Add ngPipeArgs to `ngPipe` property

demo/src/app/basic/server-side-angular-way.component.ts, demo/src/assets/docs/basic/server-side-angular-way/source-ts.md
Heroku has announced the [removal of free product plans on November 28, 2022](https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq).
An alternative platform was to use [quoddi](https://qoddi.com/).
=> chore(demo): switch angular-datatables-demo-server url #1672

package.json
Should fix the issue on #1691 and #1692 as the codelyzer depends on angular 9, which may conflict with the project angular version.
=> fix(#1691/#1692): remove dep to codelyzer

demo/src/app/advanced/using-ng-pipe.component.spec.ts, demo/src/app/advanced/using-ng-template-ref.component.spec.ts, src/angular-datatables.directive.ts
- also includes unit test
This is based on #1722 
Closes #1723
=> fix: don't crash when using `visible` on columns

demo/package.json, demo/src/app/basic/with-ajax-callback/with-ajax-callback.component.html, demo/src/app/basic/with-ajax-callback/with-ajax-callback.component.spec.ts, demo/src/app/basic/with-ajax-callback/with-ajax-callback.component.ts
@l-lin You missed a spot :P 
Also, can you trigger the docs to re-generate and deploy when you merge this? Thanks!
=> chore(demo): show static text on preview for ajax callback

demo/angular.json, demo/package-lock.json, demo/package.json, demo/src/app/app.component.html, demo/src/app/app.module.ts, demo/src/app/app.routing.ts, demo/src/app/extensions/fixed-columns-extension.component.html, demo/src/app/extensions/fixed-columns-extension.component.ts, demo/src/assets/docs/extensions/fixedcolumns/installation.md, demo/src/assets/docs/extensions/fixedcolumns/intro.md, demo/src/assets/docs/extensions/fixedcolumns/source-html.md, demo/src/assets/docs/extensions/fixedcolumns/source-ts.md, demo/src/styles.css
This feature was something I wanted to implement for a while and finally found a nice combination that works as expected. 
Thought adding this docs would be helpful for other devs in the future. 
[scrnli_12_9_2023_3-20-21 PM.webm](https://github.com/l-lin/angular-datatables/assets/4242921/674a3e71-7fc9-4939-8e05-35ba715bdef5)
=> Fixed columns extension documentation added
